# AWS URLS
EC2: "YOUR_EC2_INSTANCE_URL"
S3: "YOUR_S3_BUCKET_URL"
POSTGRESQL: "YOUR_RDS_POSTGRESQL_URL"

# KAGGLE CREDENTIALS
KAGGLE_USERNAME: "rafaelgreca"
KAGGLE_KEY: "3c624a1ff3046e98071167741b441b89"

# AWS CREDENTIALS
AWS_ACCESS_KEY: "YOUR_AWS_ACCESS_KEY"
AWS_SECRET_KEY: "YOUR_AWS_SECRET_KEY"
