FEATURES: ['Gender_x0_Male', 'Age_x0_q3', 'Age_x0_q4', 'FAVC_x0_yes', 'CAEC_x0_Frequently', 'SCC_x0_yes', 'CALC_x0_no', 'EVEMM_x0_1', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE', 'BMI', 'PAL', 'IBW']
MODEL_NAME: 'lightgbm'
MODEL_FLAVOR: 'lightgbm'
RUN_ID: 'f4850bdd98344071a4f73053868f9993'
EXPERIMENT_ID: '616296920000275133'
VERSION: '2.0'
