RAW_FILE_NAME: 'Original_ObesityDataSet.csv' # the data used to train and validate the model
CURRENT_FILE_NAME: 'Current_ObesityDataSet.csv' # the new data used to monitor the model
TARGET_COLUMN: 'NObeyesdad'
DATA_PATH: '/media/greca/HD/GitHub/e2e-mlops-project//data/'
ARTIFACTS_PATH: '/media/greca/HD/GitHub/e2e-mlops-project//models/artifacts/'
FEATURES_PATH: '/media/greca/HD/GitHub/e2e-mlops-project//models/features/'
RESEARCH_ENVIRONMENT_PATH: '/media/greca/HD/GitHub/e2e-mlops-project//notebooks/'
