# MODEL SETTINGS
FEATURES: ['Gender_x0_Male', 'Age_x0_q2', 'Age_x0_q4', 'CAEC_x0_Frequently', 'CAEC_x0_Sometimes', 'CAEC_x0_no', 'SMOKE_x0_yes', 'SCC_x0_yes', 'CALC_x0_infrequent_sklearn', 'MTRANS_x0_Public_Transportation', 'MTRANS_x0_Walking', 'MTRANS_x0_infrequent_sklearn', 'IS_x0_1', 'FCVC', 'FAF', 'TUE', 'BMI', 'BMR']
MODEL_NAME: 'xgboost'
MODEL_FLAVOR: 'xgboost'
RUN_ID: 'e7d3cea9b93b4dd18ae421c402520a2c'
EXPERIMENT_ID: '708342276728582022'
VERSION: '1.0'

# GENERAL SETTINGS
DATA_PATH: '/media/greca/HD/GitHub/e2e-mlops-project/data/'
RAW_FILE_NAME: 'Original_ObesityDataSet.csv'
ARTIFACTS_PATH: '/media/greca/HD/GitHub/e2e-mlops-project/models/artifacts/'
FEATURES_PATH: '/media/greca/HD/GitHub/e2e-mlops-project/models/features/'
RESEARCH_ENVIRONMENT_PATH: '/media/greca/HD/GitHub/e2e-mlops-project/notebooks/'
TARGET_COLUMN: 'NObeyesdad'
LOG_LEVEL: 'INFO'
LOG_PATH: '/media/greca/HD/GitHub/e2e-mlops-project/'
