name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker dev image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:notebooks"
          file: Dockerfile.dev
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/e2e-dev:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/e2e-dev:latest
          cache-to: type=inline
      -
        name: Build and push Docker prod image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/e2e-prod:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/e2e-prod:latest
          cache-to: type=inline
