name: Pylint

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Building Application
      uses: ./.github/actions/build-application

    - name: Analysing the code with Pylint
      run: |
        pip install pylint
        pylint $(git ls-files '*.py') --rcfile=.pylintrc
